//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class PTZSettings {
    
    private PTZSettingsCamera[] cameraField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Camera")]
    public PTZSettingsCamera[] Camera {
        get {
            return this.cameraField;
        }
        set {
            this.cameraField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PTZSettingsCamera {
    
    private string commandURLField;
    
    private PTZSettingsCameraCommands commandsField;
    
    private string makeField;
    
    private string versionField;
    
    private byte idField;
    
    /// <remarks/>
    public string CommandURL {
        get {
            return this.commandURLField;
        }
        set {
            this.commandURLField = value;
        }
    }
    
    /// <remarks/>
    public PTZSettingsCameraCommands Commands {
        get {
            return this.commandsField;
        }
        set {
            this.commandsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Make {
        get {
            return this.makeField;
        }
        set {
            this.makeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PTZSettingsCameraCommands {
    
    private string centerField;
    
    private string leftField;
    
    private string leftUpField;
    
    private string rightField;
    
    private string rightUpField;
    
    private string upField;
    
    private string downField;
    
    private string leftDownField;
    
    private string rightDownField;
    
    private string stopField;
    
    private string zoomInField;
    
    private string zoomOutField;
    
    private PTZSettingsCameraCommandsCommand[] extendedCommandsField;
    
    /// <remarks/>
    public string Center {
        get {
            return this.centerField;
        }
        set {
            this.centerField = value;
        }
    }
    
    /// <remarks/>
    public string Left {
        get {
            return this.leftField;
        }
        set {
            this.leftField = value;
        }
    }
    
    /// <remarks/>
    public string LeftUp {
        get {
            return this.leftUpField;
        }
        set {
            this.leftUpField = value;
        }
    }
    
    /// <remarks/>
    public string Right {
        get {
            return this.rightField;
        }
        set {
            this.rightField = value;
        }
    }
    
    /// <remarks/>
    public string RightUp {
        get {
            return this.rightUpField;
        }
        set {
            this.rightUpField = value;
        }
    }
    
    /// <remarks/>
    public string Up {
        get {
            return this.upField;
        }
        set {
            this.upField = value;
        }
    }
    
    /// <remarks/>
    public string Down {
        get {
            return this.downField;
        }
        set {
            this.downField = value;
        }
    }
    
    /// <remarks/>
    public string LeftDown {
        get {
            return this.leftDownField;
        }
        set {
            this.leftDownField = value;
        }
    }
    
    /// <remarks/>
    public string RightDown {
        get {
            return this.rightDownField;
        }
        set {
            this.rightDownField = value;
        }
    }
    
    /// <remarks/>
    public string Stop {
        get {
            return this.stopField;
        }
        set {
            this.stopField = value;
        }
    }
    
    /// <remarks/>
    public string ZoomIn {
        get {
            return this.zoomInField;
        }
        set {
            this.zoomInField = value;
        }
    }
    
    /// <remarks/>
    public string ZoomOut {
        get {
            return this.zoomOutField;
        }
        set {
            this.zoomOutField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Command", IsNullable=false)]
    public PTZSettingsCameraCommandsCommand[] ExtendedCommands {
        get {
            return this.extendedCommandsField;
        }
        set {
            this.extendedCommandsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PTZSettingsCameraCommandsCommand {
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}
